### ISSUE TITLE
Websites disappearing from overview

### ISSUE THREAD

**Issue by kroese** [Eugeny/ajenti-v#120]
Today I discovered that the last couple of websites that I configured using Ajenti V are missing from the overview. The strange thing is that Nginx is still serving this websites, and they are still available in '/etc/nginx/conf.d/'. So everything seems normal.

How can it be that they don't show up in the control panel, and whats steps are needed to restore them again?

**Comment by noogen** [comment]
Your /etc/ajenti/vh.json got lost/corrupted somehow.
