### ISSUE TITLE
Drop-in Replacement from MySQL to MariaDB

### ISSUE THREAD

**Issue by Ardakilic** [Eugeny/ajenti-v#128]
Hello,

I'm using ajenti + ajenti-v in my Ubuntu 14.04 x64 and I'm quite happy with it. 

I want to switch from MySQL to MariaDB, but I've encountered an error:

To Drop-in switch, I've removed MySQL and installed MariaDB as described in [this answer](http://askubuntu.com/a/532453/107722).

Since it's 100% compatible with MySQL, all databases created previously work great with MariaDB at this stage.

While removing `mysql-server`, as expected, `ajenti-v-mysql` is also removed.

After installation of MariaDB, I've tried to reinstall `ajenti-v-mysql`, but I get this error:

```
root@playground:~# apt-get install ajenti-v-mysql
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ajenti-v-mysql : Depends: mysql-server but it is not going to be installed
                  Depends: mysql-client
E: Unable to correct problems, you have held broken packages.
```

How can I overcome this issue? Could there be a transparent package something like `ajenti-v-mariadb`, which is exactly same as `ajenti-v-mysql` but depends `mariadb-server` (and maybe `mariadb-client` ?) instead?

Thanks in advance,

**Comment by sajidunnar** [comment]
Hello ,

I am into same issue want to upgrade the mysql to 5.6 but getting following errors of depdencies

The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ajenti-v-mysql : Depends: mysql-server but it is not going to be installed or
                           mariadb-server but it is not going to be installed
                  Depends: mysql-client or
                           mariadb-client but it is not going to be installed
 mariadb-client-5.5 : Depends: mariadb-client-core-5.5 (>= 5.5.44-1ubuntu0.14.04.1) but it is not going to be installed
 mysql-server-5.6 : Depends: mysql-client-5.6 (>= 5.6.27-0ubuntu0.14.04.1) but it is not going to be installed
                    Depends: mysql-server-core-5.6 (= 5.6.27-0ubuntu0.14.04.1) but it is not going to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

**Comment by Ardakilic** [comment]
@sajidunnar If it's not a must to stick on 5.x, try installing 10.x series. It seems package names on 5.x series are different. I'm using with MariaDB 10.x and still have no issues.

**Comment by sajidunnar** [comment]
Thanks Eugency ,
actually I want to run magento 2 and its require to have MySql 5.6 , let me
try MariaDB maybe it worked

On Tue, Nov 3, 2015 at 2:56 AM, Arda Kılıçdağı <notifications@github.com>
wrote:

> @sajidunnar <https://github.com/sajidunnar> If it's not a must to stick
> on 5.x, try installing 10.x series. It seems package names on 5.x series
> are different. I'm using with MariaDB 10.x and still have no issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Eugeny/ajenti-v/issues/128#issuecomment-153169783>.
>



-- 

Sajid Hussain Unar

Magento Ecommerce Consultant | Dacoders Agile Innovations

213-457-3386 | info@dacoders.com | http://www.dacoders.com

LinkedIn: http://linkedin.com/in/sajidhussain
