### ISSUE TITLE
PHP error logs

### ISSUE THREAD

**Issue by DenBeke** [Eugeny/ajenti-v#136]
I'm using Ajenti-V on Ubuntu 14, but I'm having those well-known `504 Gateway Time-out` errors. The probleem seems to be a PHP script timing out in PHP-FPM, but I don't seem to find any PHP log...

What is the default location of the PHP (error) log, using Ajenti?

**Comment by hrm143** [comment]
am using php5.6-fpm version but cannot see PHP log is at /var/log/php5.6-fpm.log or anything related to FPM error log...where and how to enable this

**Comment by Ardakilic** [comment]
@hrm143 check /var/log/nginx/sitename.error.log , it should be located there.

**Comment by hrm143** [comment]
am new to Ajenti and being using only few days after so many trails and error to upgrade to php5.6-fpm and mariadb10.1...i finally able to run Ajenti..its excellent..my CPU and RAM usage managing so well..my website is very fast now.

Seeing below...can you suggest me something to optimize? I just a learner in System admin :)
![htop](https://cloud.githubusercontent.com/assets/16494149/15669265/168ea49c-273d-11e6-8acc-67b7cbf845a0.JPG)

but am getting this error while importing product image from external URL
` 12785#0: *1095 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 45.121.188.200, server: onlyurs.com, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/ajenti-v-php5.6-fcgi-onlyurs-php5.6-fcgi-0.sock",`

and while executing a script this error (opencart)...
`12785#0: *1037 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /srv/demo/public_html/system/database/mysqli.php on line 34" while reading upstream,`

Please see screen shot of PHP.ini value
![php](https://cloud.githubusercontent.com/assets/16494149/15669183/94fa058e-273c-11e6-8da1-9f39a964a51a.JPG)

**Comment by DenBeke** [comment]
It seems that you have a problem with your PHP script...
Are you even using Caddy with Ajenti?

**Comment by DenBeke** [comment]
Ignore my previous reply... wrong issue/project
