### ISSUE TITLE
Default Virtualhost

### ISSUE THREAD

**Issue by Ardakilic** [Eugeny/ajenti-v#138]
Hello,

I have a tiny request, I hope this is considered.

In my opinion, there should be a default virtualhost setting for ajenti.

I'm using nginx, and let's say I've redirected a domain to the server's ip. If there is not a virtualhost set yet, or when I access to the ip directly, I see the first virtualhost created in alphabetical order. To be honest, this looks ugly.

Instead, it'd be awesome if there would be setting to set a virtualhost as default, or at least a default template like "the server is using Ajenti" etc.

I'd appreciate if this is considered.

Thanks again,

**Comment by Eugeny** [comment]
To make a vhost default, tick "Default" checkbox on its Ports tab.

**Comment by Ardakilic** [comment]
Thanks @Eugeny , never realized it was there. Thanks again!

**Comment by skylineservers** [comment]
Can you clarify this feature a little? We achieved the same with a vhost that started with aaaaa in the name so it would catch all requests without an existing vhost. If we check the default box for port 80 and port 443, we could name this vhost zzzzzzvhost.com and it would still catch all requests to non-existant vhosts? Thanks!

**Comment by Eugeny** [comment]
@skylineservers yes, that's exactly what it does.
