### ISSUE TITLE
ajenti-v-mail: allowed to listen more ports 

### ISSUE THREAD

**Issue by f3l1x** [Eugeny/ajenti-v#150]
I really appreciate to edit ports on SMTP. I installed ajent-v-mail with exim4. Port 25 is hardcoded into a template.

``` py
SMTP_PORT = 25
LOCAL_INTERFACES = <; 0.0.0.0.25 ; 0.0.0.0.465 ; [::0]:25 ; [::0]:465
```

I need to override it to:

``` py
SMTP_PORT = 25:587
LOCAL_INTERFACES = <; 0.0.0.0.25 ; 0.0.0.0.587 ; 0.0.0.0.465 ; [::0]:25 ; [::0]:587 ; [::0]:465
```

Is there any other way?

**Comment by Seanmcn** [comment]
Haven't tried myself, but you should be able to just add those two lines into "Mail -> Advanced -> Custom configuration"

**Comment by mystica555** [comment]
You need to add it there, but, -redefine- the macro with == and not simply = or exim will yell at you

**Comment by f3l1x** [comment]
Thank you.
