### ISSUE TITLE
Lost Config tab after changing language

### ISSUE THREAD

**Issue by noobscode** [Eugeny/ajenti-v#154]
Hello. I lost the configuration tab after switching language to Norwegian. Ive search the repo for language but I could only find translation files. 

Is there some file, table in database or command so I can change it manually back to en_US?

**Comment by Eugeny** [comment]
Language can be changed manually by editing ``/etc/ajenti/config.json`` (``language`` key)

**Comment by nordsec** [comment]
wow, thank you for super quick support!
Found it. thanks

2015-03-18 8:41 GMT+01:00 Eugene Pankov <notifications@github.com>:

> Language can be changed manually by editing /etc/ajenti/config.json (
> language key)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Eugeny/ajenti-v/issues/154#issuecomment-82796643>.
>



-- 
Mvh

Alexander A. Nordbø

Stavanger - Norway
https://HackingDefinedExperts.com <http://HackingDefinedExperts.com>
https://facebook.com/HackingDefinedExperts
http://irc.hackingdefinedexperts.com (optional: port 6667|6697 for ssl)

**Comment by nordsec** [comment]
still missing the config tab tho ?


2015-03-18 8:41 GMT+01:00 Eugene Pankov <notifications@github.com>:

> Language can be changed manually by editing /etc/ajenti/config.json (
> language key)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Eugeny/ajenti-v/issues/154#issuecomment-82796643>.
>



-- 
Mvh

Alexander A. Nordbø

Stavanger - Norway
https://HackingDefinedExperts.com <http://HackingDefinedExperts.com>
https://facebook.com/HackingDefinedExperts
http://irc.hackingdefinedexperts.com (optional: port 6667|6697 for ssl)

**Comment by Eugeny** [comment]
Check the log and/or Plugins tab, possibly the config plugin failed to load.

**Comment by nordsec** [comment]
Config plugin looks fine, logs doesent gives me any errors. Is there some
way I can reconfig ajenti.Maby reset the config file?

2015-03-18 8:51 GMT+01:00 Eugene Pankov <notifications@github.com>:

> Check the log and/or Plugins tab, possibly the config plugin failed to
> load.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Eugeny/ajenti-v/issues/154#issuecomment-82802659>.
>



-- 
Mvh

Alexander A. Nordbø

Stavanger - Norway
https://HackingDefinedExperts.com <http://HackingDefinedExperts.com>
https://facebook.com/HackingDefinedExperts
http://irc.hackingdefinedexperts.com (optional: port 6667|6697 for ssl)

**Comment by Eugeny** [comment]
Could you please run ``service ajenti stop; ajenti-panel -v``, log into the panel and check if there are any errors in the console?

**Comment by nordsec** [comment]
I dont get any errors in the console but I got this error when starting
ajenti:

Den onsdag 18. mars 2015 skrev Eugene Pankov <notifications@github.com>
følgende:

> Could you please run service ajenti stop; ajenti-panel -v, log into the
> panel and check if there are any errors in the console?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Eugeny/ajenti-v/issues/154#issuecomment-82812304>.
>


-- 
Mvh

Alexander A. Nordbø

Stavanger - Norway
https://HackingDefinedExperts.com <http://HackingDefinedExperts.com>
https://facebook.com/HackingDefinedExperts
http://irc.hackingdefinedexperts.com (optional: port 6667|6697 for ssl)

**Comment by Eugeny** [comment]
Unfortunately you can't post attachments via mail here.

**Comment by nordsec** [comment]
Here is the output service ajenti stop; ajenti-panel -v
http://pastebin.com/4eKE6w74

**Comment by Eugeny** [comment]
Strange. Have you by any chance disabled Configurator access for your user? Or are you logging in as root?

**Comment by nordsec** [comment]
Yes Im root. Think its very strange.

**Comment by nordsec** [comment]
when you have a chanse. let me pass over some credentials so you can check it yourself

**Comment by Eugeny** [comment]
You can mail them securely to e@ajenti.org, and I'll check it out tomorrow
morning.

**Comment by meeyou33** [comment]
Having the same issue after trying to duplicate the root account. Configuration tab is missing and no errors in ajenti-panel -v. There is one warning though:

13.05.2015 10:52 __init__.py:340               WARN   *** [elements] Plugin error: format error
