### ISSUE TITLE
File manager doesnt support download

### ISSUE THREAD

**Issue by kroese** [Eugeny/ajenti-v#157]
Feature-request:

You can upload and extract zip-files from the file manager, but you cannot do the opposite: download files or zip directories.

**Comment by stopspazzing** [comment]
agreed, cant download files from server...not sure why this wasnt but upload file was added. Curious why hasnt been moved to IDEA?

**Comment by mikestp27** [comment]
I agree it would be useful; but should probable be listed under ajenti instead of ajenti-v...

**Comment by kroese** [comment]
Duplicate of ajenti/ajenti#582
