### ISSUE TITLE
Debian Squeeze 64bit packages but I did not find ...

### ISSUE THREAD

**Issue by jarinokovac** [Eugeny/ajenti-v#16]
I wish a nice day,
I have the operating system debian squeeze 64bit packages but I did not find ... :/

Console log:
root@biznisweb:~# apt-get install ajenti-v ajenti-v-nginx ajenti-v-mysql ajenti-v-php-fpm
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package ajenti-v
E: Unable to locate package ajenti-v-nginx
E: Unable to locate package ajenti-v-mysql
E: Unable to locate package ajenti-v-php-fpm

Smith.

**Comment by alijaffar** [comment]
I got this same error, 
<code>apt-get install ajenti-v ajenti-v-nginx ajenti-v-mysql ajenti-v-php-fpm php5-mysql
</code>

**Comment by alijaffar** [comment]
E: Unable to locate package ajenti-v
E: Unable to locate package ajenti-v-nginx
E: Unable to locate package ajenti-v-mysql
E: Unable to locate package ajenti-v-php-fpm

**Comment by christoferw** [comment]
i get this: http://repo.ajenti.org main InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY BDC3FBAA53029759 

after i run:
echo "deb http://repo.ajenti.org/debian main main debian" >> /etc/apt/sources.list
apt-get update
