### ISSUE TITLE
MariaDB upgrade

### ISSUE THREAD

**Issue by wrrr** [Eugeny/ajenti-v#171]
I do not have MySql tab in "Websites" since upgrade. Websites running as expected. Ubuntu 14.04.2

--

14.05.2015 11:12 ajenti-panel:105
INFO  Using config file /etc/ajenti/config.json
Traceback (most recent call last):
  File "/usr/bin/ajenti-panel", line 107, in <module>
    os.chmod(config_file, stat.S_IRWXU)
OSError: [Errno 1] Operation not permitted: '/etc/ajenti/config.json'

**Comment by wrrr** [comment]
I ran service ajenti stop; ajenti-panel -v as root and no errors.

Mysterious the mysql tab still missing in websites.

**Comment by wrrr** [comment]
[resolved] mysql plugin files corrupted during mariadb installation

**Comment by hrm143** [comment]
Is MariaDB 10.1 supported? i have upgraded before but mysqlTAB on website disappear. Someone please guide how to install latest Mariadb10.1 on Ubuntu 14.04 or later

**Comment by Ardakilic** [comment]
I'm using with MariaDB 10.1 just fine.

@hrm143 just follow this: https://downloads.mariadb.org/mariadb/repositories/
