### ISSUE TITLE
Possible to use Ajenti-V with NGINX 1.9 ?

### ISSUE THREAD

**Issue by MaximKiselev** [Eugeny/ajenti-v#179]

**Comment by Eugeny** [comment]
Yes, it can be used with any NGINX version as long as it's looking for the configuration in /etc/nginx/nginx.conf

**Comment by MaximKiselev** [comment]
Expected to install this version of the software in the standard distribution ?

**Comment by Eugeny** [comment]
Работать будет в любом случае, пакет можно брать из репозиториев, можно собрать самому.

**Comment by MaximKiselev** [comment]
Во так лучше, проблема в незнакомстве с данным сервером (а апрегдиться нормально не дает, вылезают косяки на Debian 8.1).
