### ISSUE TITLE
Same directory is shared by users

### ISSUE THREAD

**Issue by l4sh** [Eugeny/ajenti-v#183]
The same root directory is available to all users meaning they can modify other users files.

This could be resolved by adding an user start and root directory setting per user in the user configuration.

**Comment by cronner** [comment]
really big problem, needs to be seperated, one of my Wordpress site got hacked, and they got access to all my files because it's the same user

**Comment by Sithira** [comment]
Cant you use Symlinks?

**Comment by l4sh** [comment]
I actually implemented some of this back then in [l4sh/ajenti](https://github.com/l4sh/ajenti/tree/feature/user_folder_isolation) but found some other issues and did not have the time to continue working on it. I don't know if this feature was later implemented in Ajenti.

Since I reported this on the wrong repo (should be on ajenti) I'll close this issue.
