### ISSUE TITLE
User Files Under /etc/nginx/ being deleted

### ISSUE THREAD

**Issue by gxgani** [Eugeny/ajenti-v#191]
I am trying to setup a simple htpasswd file based login under /etc/nginx but it seems that the folder is recreated every time we change from the control panel. I currently managed to move the password file else where but can there be an exclusion or ways to prevent users files from being deleted?

**Comment by Eugeny** [comment]
Hi, no, /etc/nginx is completely auto-generated by Ajenti V. You are being warned about this before activating Ajenti V for the first time. However, placing .conf files /etc/nginx.custom.d will auto-include them into nginx.conf.

**Comment by chimit** [comment]
Today I opened Ajenti's web-sites tab and saw a message that config will be rewritten. It was strange, because I had been using Ajenti for long time. I chose OK and lost all my sites configs. Does Ajenti make backups of nginx.conf before overriding?

/etc/nginx.custom.d folder is empty.
