### ISSUE TITLE
PHP7 support

### ISSUE THREAD

**Issue by Ardakilic** [Eugeny/ajenti-v#206]
Hello,

First of all, thank you for Ajenti + Ajenti-v, I've been using more than a year in my personal server, and I must say this is the best admin panel I've ever used.

I've a question, I hope you can help me.

Does Ajenti-v support PHP7 as of now ?

I have updated a VPS that doesn't have a control panel, which is running Ubuntu server 14.04 with [this PPA](https://launchpad.net/~ondrej/+archive/ubuntu/php-7.0).

[This article](https://bjornjohansen.no/upgrade-to-php7) can be a reference for updating Ubuntu.

Path is changed like `/etc/php/7.0/fpm`

This guy's PPA is the most popular one around, and works as a treat with PHP5.6 + Ajenti-v.

From what I see from [phpfpm.py](https://github.com/Eugeny/ajenti-v/blob/master/vh-php-fpm/phpfpm.py), I can assume Ajenti-v won't work with PHP7.

So my question goes:

Are there any plans to update Ajenti-v-php-fpm for PHP7? Or Is there going to be another package?

Here's the current PHP7 package list if that would help:

```shell
➜  /srv  apt-cache search php7
php7.0-common - Common files for packages built from the PHP source
libapache2-mod-php7.0 - server-side, HTML-embedded scripting language (Apache 2 module)
php7.0-cgi - server-side, HTML-embedded scripting language (CGI binary)
php7.0-cli - command-line interpreter for the PHP scripting language
php7.0-phpdbg - server-side, HTML-embedded scripting language (PHPDBG binary)
php7.0-fpm - server-side, HTML-embedded scripting language (FPM-CGI binary)
libphp7.0-embed - HTML-embedded scripting language (Embedded SAPI library)
php7.0-dev - Files for PHP7.0 module development
php7.0-dbg - Debug symbols for PHP7.0
php7.0-curl - CURL module for PHP
php7.0-gd - GD module for PHP
php7.0-imap - IMAP module for PHP
php7.0-intl - Internationalisation module for PHP
php7.0-ldap - LDAP module for PHP
php7.0-pgsql - PostgreSQL module for PHP
php7.0-pspell - pspell module for PHP
php7.0-recode - recode module for PHP
php7.0-snmp - SNMP module for PHP
php7.0-tidy - tidy module for PHP
php7.0 - server-side, HTML-embedded scripting language (metapackage)
php7.0-json - JSON module for PHP
php-all-dev - package depending on all supported PHP development packages
php7.0-sybase - Sybase module for PHP
php7.0-modules-source - PHP 7.0 modules source package
php7.0-sqlite3 - SQLite3 module for PHP
php7.0-mysql - MySQL module for PHP
php7.0-opcache - Zend OpCache module for PHP
```

Thanks in advance,

Best Regards,

**Comment by eserozvataf** [comment]
+1

**Comment by demirhancosku** [comment]
+1.5

**Comment by cronner** [comment]
+1

**Comment by ShadowXVII** [comment]
+1

**Comment by Seanmcn** [comment]
Also interested to hear on plans for this

**Comment by EvgeniiShumeiko** [comment]
+1
I install php7, it have a php-fpm 7.0 version but ajenti-v-php-fpm have php-fpm 5.9 version
P.S I am sorry, my english is bad((

**Comment by Ardakilic** [comment]
Anyone reading this and willing to contribute, to ease the process for @Eugeny , especially if you're using RedHat, CentOS etc. , can you please install PHP7 on a "dummy, non production, test" server and provide how you've upgraded, the updated directory paths (`/etc/php/7.0/fpm` etc.), package names (`php7.0-fpm`) etc. ?

**Comment by arifr007** [comment]
+1
i would like to try and be a beta tester if @Eugeny starting the development. :D

**Comment by alessiodionisi** [comment]
I'm trying it on ubuntu

**Comment by alessiodionisi** [comment]
Hi guys, I have almost completed the plugin for ajenti v :D

**Comment by Ardakilic** [comment]
Great job @alessiodionisi ! :)

**Comment by alessiodionisi** [comment]
Thanks! @Ardakilic

**Comment by arifr007** [comment]
nice job @alessiodionisi

**Comment by SergeyMiracle** [comment]
Debian with dotdeb
Folder - `/etc/php/7.0/fpm`
Service - php-fpm

Everything works except ajenti-v-php-fpm :cry:

**Comment by alessiodionisi** [comment]
Update patched files for php7.0 & php5.6: https://github.com/Eugeny/ajenti-v/pull/213

**Comment by Ardakilic** [comment]
I'm closing this in favor of #213.

Upgrading was quite easy on Ubuntu 14.04 for me:

* Backup
* Remove PHP5 packages from server
* Remove ajenti PHP Fpm package
* Install PHP7 from ondrej's PPA (for the time being)
* Install new Ajenti daemon
* For all websites, I've to remove content (php5-fpm) and reconfigure FPM:
    * FPM pattern was not identified for me so I had to set it manually: 
    I've set URL pattern: `\.php$` and type regex
* Restart Ajenti daemons
* Restart php.x-fpm and nginx both
* Then restart Ajengi daemon again (I don't know why, but I had to do these in this order for the websites pop up)

And I'm using PHP7 in my server along with ajenti

Thanks again, @alessiodionisi for the work done! :smile:

**Comment by khalilst** [comment]
@Ardakilic, you're a man, your middle name must be superman.
Changing content tab manually save my night
