### ISSUE TITLE
[Feature Request] Email server (Dovecot / Postfix)

### ISSUE THREAD

**Issue by karbowiak** [Eugeny/ajenti-v#23]
As the title states, having an email server with ajenti would be awesome.

I use the following setup myself
https://library.linode.com/email/postfix/postfix2.9.6-dovecot2.0.19-mysql
with the dspam, dkim and full text search from here:
http://sealedabstract.com/code/nsa-proof-your-e-mail-in-2-hours/

If i was more proeffecient at python, i'd most likely have thrown myself out into getting it working, sadly, i am not

**Comment by stuudent** [comment]
+1

**Comment by ApfelUser** [comment]
:+1:

**Comment by chrko** [comment]
Why was this issue closed without a comment?

**Comment by Eugeny** [comment]
Because Ajenti-V already comes with Courier+Exim4 mail server support.

**Comment by chrko** [comment]
But this no argument.
So you don't want to support other mail systems, or you just don't want to develop it and patches are welcome?

**Comment by Eugeny** [comment]
Sorry, I possibly misunderstood the request. It says "Email server", and at that time there was no mail support in Ajenti V. I've closed it as soon as the mail plugin was implemented. Naturally, pull requests are welcome at all times.

**Comment by chrko** [comment]
Ah, okay! I really want dovecot because courier is the saurian in my eyes ;)
I think I will dig into and test the panel in the next days (currently I don't use any management software).

**Comment by AbbyNormal** [comment]
You should really switch to postfix and dovecot because they are superior. Postfix is a better performance mail server, it surpases exim in every way, including the easier configuration files and syntax. In benchmarks postfix can push whole a lot of emails more than exim.
