### ISSUE TITLE
Ajenti... dead?

### ISSUE THREAD

**Issue by bbbenji** [Eugeny/ajenti-v#238]
Looks like development has slowed down to a stop. I thought this project had a lot of promise and at the time active development. Because of this I chose it to administer our dedicated server with 20+ sites. It has done almost everything I wanted but still lacks features and has a growing list of unresolved issues and pull requests. 

This shows that interest is there from the community! Just looks like the developers have either lost time or lost their interest.

Perhaps it will pick up again, perhaps a new fork will rise. Great work so far. I hope to see this project continue, I am sure I am not alone.

**Comment by raykai** [comment]
i would like to see a V for Ajenti 2

**Comment by psycholyzern** [comment]
Sad to see this project died.
