### ISSUE TITLE
php-fpm pools should be saved into separate files in pool.d

### ISSUE THREAD

**Issue by Koopzington** [Eugeny/ajenti-v#245]
We just saw that the pools for each site are being written into php-fpm.conf.
A default php-fpm.conf has

```
include=/etc/php/7.0/fpm/pool.d/*.conf
```

Since the file is bein generated this line is missing and users aren't able to put files into pool.d.
I'd prefer to have the php-fpm.conf completely untouched by ajenti and rather let ajenti write a file inside pool.d for each pool or if that's too complicated, let it write one pool.d/ajenti.conf so users can still use pool.d

**Comment by noogen** [comment]
I've been playing with this myself recently inside of a docker container: https://github.com/niiknow/ajenti-udock/blob/master/udock/ajenti-v/vh-php7.0-fpm/php70fpm.py

I have some more testing an experimentation to go before I feel good about trying to do a pull-request.

Right now, I have each site written into their own conf file in the pool.d folder.   The benefit is that I can add a file exists check and only write out this file if it does not exists.  That would allow for flexible customization.
