### ISSUE TITLE
Support for PHP 7.1 FPM

### ISSUE THREAD

**Issue by renanwilliam** [Eugeny/ajenti-v#251]
Hi,

It's will be interesting enable support to PHP 7.1-FPM, currently only supports 7.0

**Comment by MaximKiselev** [comment]
Maybe rebuild packages? I think ajenti must not have two subversions of programming language. Only, major version... Only two packages ajenti-v-php5-fpm and and ajenti-v-php7-fpm with latest version in backports. Or add new version of plugin for 7.1?
PHP 7.1 some faster then 7.0 and syntax

@Eugeny what do u think?

**Comment by harimayco** [comment]
I need this too +1

**Comment by kamilkrzeminski** [comment]
+1

**Comment by v-sazhin** [comment]
+1

**Comment by venigo** [comment]
+1

**Comment by noogen** [comment]
Example: https://github.com/niiknow/ajenticp/tree/master/files/var/lib/ajenti/plugins

Must modify: vh, vh-nginx, and add vh-php7.1-fpm

**Comment by FenghenHome** [comment]
Example:https://github.com/FenghenHome/ajenticp/tree/master/rootfs/var/lib/ajenti/plugins/vh-php7.1-fpm

**Comment by Sithira** [comment]
does anyone have installed php7.1-fpm ???

**Comment by pfz** [comment]
Hi, a PR has been submitted and merged concerning this issue.
#262 
Does it work for you?

**Comment by Sithira** [comment]
@pfz only if i knew how to update it . Can you guide me ?

**Comment by pfz** [comment]
@Sithira No problem. Thanks to #263 , you can use the ajenti repository to apt-get / yum the package ajenti-v-php7.1-fpm . Ok with you?

**Comment by MoNSTRiKcom** [comment]
Where  is the ajenti-v-php7.2-fpm ?

Ubuntu:
apt-cache search ajenti-v                                                                                                                        ajenti-v - Virtual hosting solution for Ajenti                                                                                                                  ajenti-v-ftp-pureftpd - PureFTPd support for Ajenti V                                                                                                           ajenti-v-ftp-vsftpd - VSFTPD support for Ajenti V                                                                                                               ajenti-v-mail - Mail for Ajenti V                                                                                                                               ajenti-v-mysql - MySQL support for Ajenti V                                                                                                                     ajenti-v-nginx - NGINX support for Ajenti V                                                                                                                     ajenti-v-nodejs - Node.JS support for Ajenti V                                                                                                                  ajenti-v-php-fpm - PHP support for Ajenti V (via PHP-FPM)                                                                                                       ajenti-v-php5.6-fpm - PHP5.6 support for Ajenti V (via PHP-FPM / ppa:ondrej/php)                                                                                ajenti-v-php7-fpm - PHP support for Ajenti V (via PHP-FPM)                                                                                                      ajenti-v-php7.0-fpm - PHP support for Ajenti V (via PHP-FPM / ppa:ondrej/php)                                                                                   ajenti-v-php7.1-fpm - PHP 7.1 support for Ajenti V (via PHP-FPM)                                                                                                ajenti-v-python-gunicorn - Python support for Ajenti V (via gunicorn)                                                                                           ajenti-v-ruby-puma - Ruby support for Ajenti V (via Puma.io)                                                                                                    ajenti-v-ruby-unicorn - Ruby support for Ajenti V (via Unicorn)

**Comment by pfz** [comment]
not implemented yet in ajenti. If you are in a rush, you can look at changes made in this PR :  #262 , so you can do the same for php 7.2 . If you do so, please consider #263 as well to make it available in the repository.

**Comment by Sithira** [comment]
@pfz i saw a merge to the main repo for php 7.2 but it was not showing up on CLI after installing.
Any idea why its not showing up ?

**Comment by MoNSTRiKcom** [comment]
@Sithira reboot ajenti :)

**Comment by renanwilliam** [comment]
Support already added
