### ISSUE TITLE
ajenti-v-nginx unable to update

### ISSUE THREAD

**Issue by FenghenHome** [Eugeny/ajenti-v#276]
dpkg-deb: error: archive '/var/cache/apt/archives/ajenti-v-nginx_0.1.50_all.deb' has premature member 'control.tar.xz' before 'control.tar.gz', giving up
dpkg: error processing archive /var/cache/apt/archives/ajenti-v-nginx_0.1.50_all.deb (--unpack):
 subprocess dpkg-deb --control returned error exit status 2
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Errors were encountered while processing:
 /var/cache/apt/archives/ajenti-v-nginx_0.1.50_all.deb

Unable to update from ajenti-v-nginx_0.1.49 to ajenti-v-nginx_0.1.50！

**Comment by Eugeny** [comment]
Rebuilt the package, try again.

**Comment by FenghenHome** [comment]
dpkg-deb: error: archive '/var/cache/apt/archives/ajenti-v-nginx_0.1.51_all.deb' has premature member 'control.tar.xz' before 'control.tar.gz', giving up
dpkg: error processing archive /var/cache/apt/archives/ajenti-v-nginx_0.1.51_all.deb (--unpack):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 /var/cache/apt/archives/ajenti-v-nginx_0.1.51_all.deb
