### ISSUE TITLE
ajenti-v-nginx unable to update

### ISSUE THREAD

**Issue by FenghenHome** [Eugeny/ajenti-v#278]
dpkg-deb: error: archive '/var/cache/apt/archives/ajenti-v-nginx_0.1.51_all.deb' has premature member 'control.tar.xz' before 'control.tar.gz', giving up
dpkg: error processing archive /var/cache/apt/archives/ajenti-v-nginx_0.1.51_all.deb (--unpack):
subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
/var/cache/apt/archives/ajenti-v-nginx_0.1.51_all.deb

Still having problems!

**Comment by Eugeny** [comment]
Fixed

**Comment by mikestp27** [comment]
Package ajenti-v-nginx 0.1.52 does not seem to be available yet... 
http://realrepo.ajenti.org:8888/debian/
