### ISSUE TITLE
PHP-FPM service showing as not running

### ISSUE THREAD

**Issue by Globegitter** [Eugeny/ajenti-v#82]
I just decided to give Ajenti (V) a test-run for one of our internal servers and I do really like it.
Set-up was quite simple, but now trying to set-up a PHP site, when I got to 'Websites' Ajenti is showing me

![capture decran 2014-07-01 a 12 39 00](https://cloud.githubusercontent.com/assets/2580254/3442453/56c853d8-0114-11e4-9a10-8c0fbfde808e.png)

Even though when I check through the server it is showing me:

![capture decran 2014-07-01 a 12 37 45](https://cloud.githubusercontent.com/assets/2580254/3442475/bf2e7ac4-0114-11e4-8cbe-f18dc43de2a3.png)

So things actually do work and it just seems to be an issue with Ajenti. Any idea what the cause could be?

Edit: I am also not even getting a simple index.php to show up. I looked at the wordpress tutorial and some other things online, but all the server seems to do when I go to the URL is downloading the .php file instead displaying what it should display. Anyone here know what the issue could be?

Any help/comment is really appreciated.

**Comment by cronner** [comment]
same here:
Ubuntu 14.04.1 LTS
Ajenti v1.2.22.17
