### ISSUE TITLE
How to install ghost on ajenti-v?

### ISSUE THREAD

**Issue by hi-caicai** [Eugeny/ajenti-v#96]
I can not install  ghost on ajenti,and the ajenti-v-nodejs
Can you help me？

**Comment by Ardakilic** [comment]
For googlers: There is a better way;

https://thesabbir.com/how-to-setup-a-ghost-blog-with-ajenti/

The following image is the screenshot my working config, make sure owner of your ghost root folder is www-data (or matches whatever you've set):

![](http://i.imgur.com/tMfq3V6.png)

And restart webistes and boom! works like a charm! 😄

**Comment by githubber** [comment]
any idea how I would insert `GHOST_NODE_VERSION_CHECK=false` in the Ajenti-V panel??

**Comment by Ardakilic** [comment]
@githubber see my example picture. You have to set/append in environment column.

Try this in environment area:

```
NODE_ENV=production GHOST_NODE_VERSION_CHECK=false
```

**Comment by githubber** [comment]
ok.

**Comment by githubber** [comment]
I tried, but it still won't start. Maybe a theme??

**Comment by Ardakilic** [comment]
Sorry, can't help further, I'm not using Ajenti anymore, but it was the way to add environment variables before running Ghost.

Try restartting Ajenti + Ajenti-v, that may help maybe.
