### ISSUE TITLE
Problems with NodeJS Environment variables

### ISSUE THREAD

**Issue by robhunt3r** [Eugeny/ajenti-v#99]
Hi,

I'm trying to set up a NodeJS site, for my site I need to export some env variables, for example:

PORT = 58080
ROOT_URL = "http://mysite.com"
DISABLE_WEBSOCKETS = true
HTTP_FORWARDED_COUNT = 1
MONGO_URL='mongodb://user:pass@127.0.0.1:27017/appDB'

I do this by going to Supervisor settings, select my app supervisor and inserting inside "Environment" box, but most of the time it doesn't work and when it does and I update/restart/whatever ajenti, thoose env variables goes empty again and again... 

It would be nice to have an option that runs first some bash profile or whatever where we can declare "export MyStuff = Whatever" before running our app... Because it's frustrating :(

**Comment by chrno1209** [comment]
Hi @robhunt3r ,
I am having issue when running my nodejs on Ajenti, if you already can run your app and have time, can you have a look at my [issue ](https://github.com/Eugeny/ajenti-v/issues/285)please?

Many thanks,
Hieu.
